# use pattern matching

# topmost directory where search starts
start_of_search:

# what should be ignored
ignore:
  - "/.Trash"

#what should not be ignored
not_ignore:
  - "/test"

#what time frame is considered
start_of_day: "6pm"
