# use pattern matching

# topmost directory where search starts
start_of_search:

# what should be ignored
ignore:
  - "*/.Trash/*"
  - "*/.local/*"

# what should be tracked
track:
  - /Users/gazelle/bash_libraries
  - /Users/gazelle/Desktop/Docker
  - /Users/gazelle/Desktop/front_end_practice
  - /Users/gazelle/Desktop/frontEnd
  - /Users/gazelle/Desktop/Iron_Yard_Ruby/iron-yard-class-work
  - /Users/gazelle/Documents/GTCC/WEB-210-Web_Design/case_project
  - /Users/gazelle/HTML
  - /Users/gazelle/Library/Containers/com.docker.docker/Data/database
  - /Users/gazelle/nanoc/documentation_project
  - /Users/gazelle/nanoc/portfolio_site/portfolio_deployment
  - /Users/gazelle/nanoc/portfolio_site/portfolio_development
  - /Users/gazelle/react_js/react_tutorial
  - /Users/gazelle/ruby/apis
  - /Users/gazelle/ruby/hangman-3
  - /Users/gazelle/ruby/indeed_scraper
  - /Users/gazelle/ruby/koans
  - /Users/gazelle/ruby/memory
  - /Users/gazelle/ruby/oo_practice
  - /Users/gazelle/ruby/scrabble
  - /Users/gazelle/ruby/shoppe
  - /Users/gazelle/ruby/what_today
  - /Users/gazelle/ruby/zarg
  - /Users/gazelle/ruby_on_rails/rails_04/blog
  - /Users/gazelle/ruby_on_rails/rails_04/crap_app
  - /Users/gazelle/ruby_on_rails/rails_04/jscript_practice
  - /Users/gazelle/ruby_on_rails/rails_04/slackers_slack
